name: coverage

on: [push, pull_request]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version: "1.25"

    - name: Test tests with coverage
      run: go test -v ./... -coverprofile=coverage.out

    - name: Upload coverage report to Codecov
      uses: codecov/codecov-action@v5
      with:
        files: coverage.out
        token: ${{ secrets.CODECOV_TOKEN }}
